// Curated action library with real emission savings
// Savings are in kg CO2e per occurrence

export const ACTIONS = [
  {
    id: "skip_meat",
    title: "Skip meat today",
    category: "diet",
    saving: 1.5,
    effort: "easy",
    emoji: "🥗",
    tip: "Beef has 20x the emissions of lentils per gram of protein. Even one skip a week adds up to 78 kg saved annually.",
    frequency: "daily",
  },
  {
    id: "veg_meal",
    title: "Cook a plant-based meal",
    category: "diet",
    saving: 0.8,
    effort: "easy",
    emoji: "🍲",
    tip: "Cooking from scratch with seasonal veg is one of the lowest-carbon meals you can eat.",
    frequency: "daily",
  },
  {
    id: "local_produce",
    title: "Buy local or seasonal produce",
    category: "diet",
    saving: 0.4,
    effort: "easy",
    emoji: "🧅",
    tip: "Airfreighted produce can have 50x the footprint of locally grown alternatives.",
    frequency: "weekly",
  },
  {
    id: "public_transport",
    title: "Use public transport",
    category: "transport",
    saving: 1.8,
    effort: "medium",
    emoji: "🚌",
    tip: "A full bus emits roughly 1/9th per passenger what a solo car journey does on the same route.",
    frequency: "daily",
  },
  {
    id: "cycle_commute",
    title: "Cycle or walk to work",
    category: "transport",
    saving: 2.2,
    effort: "medium",
    emoji: "🚴",
    tip: "Zero emissions, plus the NHS values regular cycling at £1,600/year in health savings per person.",
    frequency: "daily",
  },
  {
    id: "no_flight",
    title: "Choose train over short-haul flight",
    category: "transport",
    saving: 45.0,
    effort: "high",
    emoji: "🚄",
    tip: "London to Paris by train emits ~6 kg CO2. The same flight emits ~180 kg. Rail wins every time under 600 miles.",
    frequency: "occasional",
  },
  {
    id: "cold_wash",
    title: "Wash clothes at 30°C",
    category: "energy",
    saving: 0.6,
    effort: "easy",
    emoji: "🧺",
    tip: "Modern detergents work just as well at 30°C. Dropping from 60°C saves around 40% of the wash energy.",
    frequency: "weekly",
  },
  {
    id: "line_dry",
    title: "Line dry instead of tumble dry",
    category: "energy",
    saving: 0.5,
    effort: "easy",
    emoji: "☀️",
    tip: "Tumble dryers are energy hogs. Line drying is free, better for your clothes, and saves ~150 kg CO2 annually.",
    frequency: "weekly",
  },
  {
    id: "thermostat_down",
    title: "Turn thermostat down 1°C",
    category: "energy",
    saving: 0.45,
    effort: "easy",
    emoji: "🌡️",
    tip: "Each degree reduction saves roughly 8% on your heating bill and around 300 kg CO2 over a winter.",
    frequency: "daily",
  },
  {
    id: "unplug_devices",
    title: "Unplug devices on standby",
    category: "energy",
    saving: 0.15,
    effort: "easy",
    emoji: "🔌",
    tip: "Standby power accounts for 10% of household electricity use in the UK. Smart plugs make this effortless.",
    frequency: "daily",
  },
  {
    id: "short_shower",
    title: "Keep shower under 5 minutes",
    category: "energy",
    saving: 0.35,
    effort: "easy",
    emoji: "🚿",
    tip: "A 10-minute shower uses ~40L of hot water. Halving that saves about 130 kg CO2 per year.",
    frequency: "daily",
  },
  {
    id: "reusable_bag",
    title: "Use a reusable bag",
    category: "shopping",
    saving: 0.05,
    effort: "easy",
    emoji: "👜",
    tip: "A plastic bag is used for ~15 minutes but takes 400 years to break down. A reusable bag pays back its carbon in 5 uses.",
    frequency: "daily",
  },
  {
    id: "secondhand",
    title: "Buy secondhand instead of new",
    category: "shopping",
    saving: 2.5,
    effort: "medium",
    emoji: "♻️",
    tip: "Manufacturing new clothing accounts for 10% of global carbon emissions. Choosing secondhand breaks that cycle.",
    frequency: "occasional",
  },
  {
    id: "repair_item",
    title: "Repair instead of replace",
    category: "shopping",
    saving: 3.0,
    effort: "medium",
    emoji: "🔧",
    tip: "The highest-carbon moment in any product's life is usually when it's made. Extending its life is the most powerful intervention.",
    frequency: "occasional",
  },
];

export const CATEGORIES = {
  diet: { label: "Diet & Food", color: "#22c55e", bg: "#f0fdf4" },
  transport: { label: "Getting Around", color: "#3b82f6", bg: "#eff6ff" },
  energy: { label: "Home Energy", color: "#f59e0b", bg: "#fffbeb" },
  shopping: { label: "Shopping", color: "#a855f7", bg: "#faf5ff" },
};
